# This workflow will publish a package to npm

name: Publish Package to npmjs
run-name: Publish Package to npm by @${{ github.actor }}

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npx google-closure-compiler --js=horizontalcharts.js --js_output_file=horizontalcharts.min.js
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          
